name: ci-sonarcloud
on:
  pull_request:
     branchs:
       - develop

jobs:
  run-ci:
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v3
          with:
             go-version: 1.17
        - run: go test --coverprofile=coverage.out -v ./...
